version: '3.9'

services:




  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql
  web:
    build: .
    #image: "sagarkumar99/foodapp:latest"
    ports:
      - "8080:8080"




