version: '3.9'

services:




  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - mydb:/var/lib/mysql
  web:
    build: .
    #image: "sagarkumar99/foodapp:latest"
    ports:
      - "8081:8080"

volumes:
  mydb:


